export const archives = [
  {
    extension: "npmjs-to-npmx",
    archive: "npmjs-to-npmx.zip",
    page: "popup.html",
    background: true,
    files: [
      "manifest.json",
      "THIRD_PARTY_NOTICES.md",
      "background.js",
      "content.js",
      "redirect.js",
      "settings.js",
      "popup.html",
      "popup.css",
      "popup.js",
      "rules/packages.json",
      "rules/search.json",
      "rules/users.json",
      "rules/organizations.json",
      "icons/icon-16.png",
      "icons/icon-32.png",
      "icons/icon-48.png",
      "icons/icon-128.png",
    ],
  },
  {
    extension: "page-screenshot",
    archive: "page-screenshot.zip",
    page: "popup.html",
    background: true,
    files: [
      "manifest.json",
      "popup.html",
      "popup.css",
      "popup.js",
      "background.js",
      "capture.js",
      "icons/icon.svg",
      "icons/icon-16.png",
      "icons/icon-32.png",
      "icons/icon-48.png",
      "icons/icon-128.png",
    ],
  },
  {
    extension: "reading-list-exporter",
    archive: "reading-list-manager.zip",
    page: "popup.html",
    files: [
      "manifest.json",
      "popup.html",
      "popup.css",
      "popup.js",
      "export.js",
      "icons/icon.svg",
      "icons/icon-16.png",
      "icons/icon-32.png",
      "icons/icon-48.png",
      "icons/icon-128.png",
    ],
  },
  {
    extension: "tessera",
    archive: "tessera.zip",
    page: "newtab.html",
    files: [
      "manifest.json",
      "newtab.html",
      "newtab.css",
      "newtab.js",
      "icons.js",
      "model.js",
      "persistence.js",
      "emoji-data.json",
      "licenses/LICENSE-Geist-OFL.txt",
      "licenses/LICENSE-unicode-emoji-json-MIT.txt",
      "icons/icon.svg",
      "icons/icon-16.png",
      "icons/icon-32.png",
      "icons/icon-48.png",
      "icons/icon-128.png",
      "fonts/geist-latin-wght-normal.woff2",
      "fonts/geist-mono-latin-wght-normal.woff2",
    ],
  },
  {
    extension: "servicenow-advanced-service-view",
    archive: "servicenow-advanced-service-view.zip",
    files: [
      "manifest.json",
      "history.js",
      "redirect.js",
      "content.js",
      "rules/application-service.json",
      "icons/icon.svg",
      "icons/icon-16.png",
      "icons/icon-32.png",
      "icons/icon-48.png",
      "icons/icon-128.png",
    ],
  },
];
